CREATE TABLE GAS_READINGS(
  ID BIGSERIAL PRIMARY KEY,
  METER_ID BIGINT NOT NULL,
  READING DECIMAL NOT NULL,
  READING_DATE DATE NOT NULL,
  ACCOUNT_ID BIGINT NOT NULL
);

CREATE TABLE ELEC_READINGS(
  ID BIGSERIAL PRIMARY KEY,
  METER_ID BIGINT NOT NULL,
  READING DECIMAL NOT NULL,
  READING_DATE DATE NOT NULL,
  ACCOUNT_ID BIGINT NOT NULL
);

CREATE TABLE ACCOUNTS(
  ACCOUNT_ID BIGINT PRIMARY KEY
);

ALTER TABLE GAS_READINGS ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID);
ALTER TABLE ELEC_READINGS ADD FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID);